spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SmartAccount?useSSL=false
    username: root
    password: 6Rd2a4y0A
    useSSL: false
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true